name: Release Please (disabled)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: false # disabled in favor of release-it
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          

